### ISSUE TITLE
Python2: name 'cat' is not defined.

### ISSUE THREAD

**Issue by Alfro** [Fredster64/Randomly-Generated-Maze#14]
The game errors when selecting the character, if using Python 2.7. This is due to the use of "input()".
```
  File "/home/alfro/projects/Randomly-Generated-Maze/MazeIncludes.py", line 202, in getSprites
    answer = input()
```
This didn't take long to figure out, but maybe the README should have a note pointing that this is meant to be run on python 3

Full error (for completion's sake):
```
(venv2) ➜  Randomly-Generated-Maze master ✗ python Maze.py    
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Welcome to the maze!
You start in the top-left corner and can move left, right, up or down.
Please choose how long and wide you want the maze to be.
What length? 20
What width? 20
Would you like to play as a cat or a dog?
cat
Traceback (most recent call last):
  File "Maze.py", line 14, in <module>
    main()
  File "Maze.py", line 9, in main
    gameEngine = GameEngine()
  File "/home/alfro/projects/Randomly-Generated-Maze/GameEngine.py", line 24, in __init__
    playerSpriteDict = getSprites(0)
  File "/home/alfro/projects/Randomly-Generated-Maze/MazeIncludes.py", line 202, in getSprites
    answer = input()
  File "<string>", line 1, in <module>
NameError: name 'cat' is not defined

```

**Comment by freddiewpayne** [comment]
Thanks for bringing this up! I've added a disclaimer to to README saying that the game won't run on Python2, as suggested.
